version: "3.8"
name: "soundunder"

# Layer Architecture
services:
  # Data Layer
  #auth_db:
  SoundUNder_auth_db:
    extends:
      file: ./data/docker-compose.yml
      service: SoundUNder_auth_db

  #audio_db:
  db:
    extends:
      file: ./data/docker-compose.yml
      service: db

  # #library_db:
  library_db:
    extends:
      file: ./data/docker-compose.yml
      service: library_db

  #search_db:
  search_db:
    extends:
      file: ./data/docker-compose.yml
      service: search_db

  #analysis_db:
  mongo_analysis:
    extends:
      file: ./data/docker-compose.yml
      service: mongo_analysis

  # Logic Layer
  #auth_ms:
  SoundUNder_auth_ms:
    extends:
      file: ./logic/SoundUNder_auth_ms/docker-compose.yml
      service: su_auth_ms
    depends_on:
      - SoundUNder_auth_db
    links:
      - SoundUNder_auth_db

  #audio_ms:
  ms:
    extends:
      file: ./logic/SoundUNder_audio_ms/docker-compose.yml
      service: ms
    depends_on:
      - db
    links:
      - db

  # Message Broker ***
  rabbitmq:
    extends:
      file: ./mq/docker-compose.yml
      service: rabbitmq
    networks:
      - soundunder_network

  #analysis_ms:
  analysis_ms:
    extends:
      file: ./logic/SoundUNder_analysis_ms/docker-compose.yml
      service: analysis_ms
    depends_on:
      - rabbitmq
      - mongo_analysis
    links:
      - rabbitmq
      - mongo_analysis
    networks:
      - soundunder_network

  #library_ms:
  sistema_library_ms:
    extends:
      file: ./logic/SoundUNder_library_ms/docker-compose.yml
      service: sistema_library_ms
    depends_on:
      - library_db

  #search_ms:
  soundunder_search_ms:
    extends:
      file: ./logic/SoundUNder_search_ms/docker-compose.yml
      service: soundunder_search_ms
    depends_on:
      - search_db
    links:
      - search_db

  # Integration Layer
  SoundUNder_ag:
    extends:
      file: ./integration/SoundUNder_ag/docker-compose.yml
      service: api-gateway
    depends_on:
      - rabbitmq
      - analysis_ms
      - SoundUNder_auth_ms
      - ms
      - sistema_library_ms
      - soundunder_search_ms

    links:
      - rabbitmq
      - analysis_ms
      - SoundUNder_auth_ms
      - ms
      - sistema_library_ms
      - soundunder_search_ms
      # environment:
      #   - AUTH_MS_BASE_URL=http://SoundUNder_auth_ms:3000
      #   - AUDIO_MS_BASE_URL=http://college-ms:8080
      #   # - FRONTEND_URL=https://localhost

      #Presentation Layer
      #wa:
  SoundUNder_wa:
    extends:
      file: ./apps/SoundUNder_wa/docker-compose.yml
      service: SoundUNder_wa
    depends_on:
      - SoundUNder_ag
    links:
      - SoundUNder_ag

networks:
  soundunder_network:
    driver: bridge

volumes:
  su_auth_db_data:
  mysql_data: # mongo_data:
  SoundUNder_search_ms:

  search_data:
  lib_db_data:
  lib_db_config:
