version: "3.8"
name: "soundunder"

# Layer Architecture
services:
  # Data Layer
  #auth_db:
  SoundUNder_auth_db:
    extends:
      file: ./data/docker-compose.yml
      service: SoundUNder_auth_db

  #audio_db:
  db:
    extends:
      file: ./data/docker-compose.yml
      service: db

  #library_db:
  mongo:
    extends:
      file: ./data/docker-compose.yml
      service: mongo

  #search_db:
  search_db:
    extends:
      file: ./data/docker-compose.yml
      service: search_db

  # Logic Layer
  #auth_ms:
  SoundUNder_auth_ms:
    extends:
      file: ./logic/SoundUNder_auth_ms/docker-compose.yml
      service: su_auth_ms
    depends_on:
      - SoundUNder_auth_db
    links:
      - SoundUNder_auth_db

  #audio_ms:
  ms:
    extends:
      file: ./logic/SoundUNder_audio_ms/docker-compose.yml
      service: ms
    depends_on:
      - db
    links:
      - db

  # Message Broker ***
  rabbitmq:
    extends:
      file: ./mq/docker-compose.yml
      service: rabbitmq

  #analysis_ms:
  analysis_ms:
    extends:
      file: ./logic/SoundUNder_analysis_ms/docker-compose.yml
      service: analysis_ms
    depends_on:
      - rabbitmq

  #library_ms:
  library_ms:
    extends:
      file: ./logic/SoundUNder_library_ms/docker-compose.yml
      service: library_ms
    depends_on:
      - mongo

  #search_ms:
  search_ms:
    extends:
      file: ./logic/SoundUNder_search_ms/docker-compose.yml
      service: app
    depends_on:
      - search_db

  # Integration Layer
  SoundUNder_ag:
    extends:
      file: ./integration/SoundUNder_ag/docker-compose.yml
      service: api-gateway
    depends_on:
      - SoundUNder_auth_ms
      - ms
      #- rabbitmq

    links:
      - SoundUNder_auth_ms
      - ms
      #- rabbitmq

    environment:
      - AUTH_MS_BASE_URL=http://SoundUNder_auth_ms:3000
      - AUDIO_MS_BASE_URL=http://college-ms:8080

      - FRONTEND_URL=https://localhost

volumes:
  su_auth_db_data:
  mysql_data:
  mongo_data:
  search_data:
